name : Criando Pacotes de Release
on:
  workflow_dispatch:
    inputs:
     tag_name:
         description: 'Nome da Tag para a Release(ex: v1.0.0)'
         required: true
     release_name:
         description: 'Nome da Release (ex: Versão 1.0.0)'
         required: true
     prerelease:
         description: 'Marcar como Pre-release?'
         required: false
         default: false
         type: boolean
     
jobs:
  create_release_packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Criar Pacote Zip
        id: zip_repo 
        uses: thedoctor0/zip-release@.0.7.6
        with:
          type: 'zip'
          file_name: 'repo-package.zip'

      - name: Criar Release
        uses: ncipollo/release-action@v1.14.0
        with:
            tag: ${{ github.event.inputs.tag_name }}
            name: ${{ github.event.inputs.release_name }}
            prerelease: ${{ github.event.inputs.prerelease }}
            files: repo-package.zip
        